<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit41933c92e24e648399045cc3d504f15f
{
    public static $prefixLengthsPsr4 = array (
        'J' => 
        array (
            'JsonSchema\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'JsonSchema\\' => 
        array (
            0 => __DIR__ . '/..' . '/justinrainbow/json-schema/src/JsonSchema',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit41933c92e24e648399045cc3d504f15f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit41933c92e24e648399045cc3d504f15f::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
